// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeEU7kd838uS3yTzJZR3fgU5eA4i4YsPc',
    appId: '1:581821496352:web:74aca3ecc77fb71c3a5045',
    messagingSenderId: '581821496352',
    projectId: 'assesment-47fff',
    authDomain: 'assesment-47fff.firebaseapp.com',
    storageBucket: 'assesment-47fff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfkzouw5qZhi8qSAh_P6Yowa76YsQZd9U',
    appId: '1:581821496352:android:613971339058e2b23a5045',
    messagingSenderId: '581821496352',
    projectId: 'assesment-47fff',
    storageBucket: 'assesment-47fff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-93JD_iAvc6N4IK6JRvR2HAANIxj2Zg',
    appId: '1:581821496352:ios:aa7bc65163d387d33a5045',
    messagingSenderId: '581821496352',
    projectId: 'assesment-47fff',
    storageBucket: 'assesment-47fff.firebasestorage.app',
    iosBundleId: 'com.example.assesmentFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-93JD_iAvc6N4IK6JRvR2HAANIxj2Zg',
    appId: '1:581821496352:ios:aa7bc65163d387d33a5045',
    messagingSenderId: '581821496352',
    projectId: 'assesment-47fff',
    storageBucket: 'assesment-47fff.firebasestorage.app',
    iosBundleId: 'com.example.assesmentFlutter',
  );
}
